baseURL: 'https://avlihachev.github.io/'
languageCode: 'en-us'
title: 'Aleksandr Likhachev'
theme: 'PaperMod'

#menu:
#    main:
#        - name: Blog
#          url: post
#          weight: 5
#        - name: Search
#          url: search/
#          weight: 10
#        - name: About
#          url: about
#          weight: 10
params:
    #env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Aleksandr Likhachev
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    #ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: "personal pages" # optional default will be site title
        subtitle: "software engineer"
        imageUrl: "/images/profile.jpg" # optional
        #imageTitle: "<title of image as alt>" # optional
        #imageWidth: 120 # custom size
        #imageHeight: 120 # custom size
#        buttons:
#            - name: Archive
#              url: "/archive"
#            - name: Github
#              url: "https://github.com/"
    
    socialIcons: # optional
        - name: github
          url: "https://github.com/avlihachev"
        - name: twitter
          url: "https://twitter.com/lihachev"
        - name: instagram
          url: "https://instagram.com/lihachev"
        - name: linkedin
          url: "https://www.linkedin.com/in/alexander-lihachev-b893468"
        - name: facebook
          url: "https://facebook.com/lihachev"  
    #homeInfoParams:
    #    Title: "Personal pages"
    #    Content: >
    #        Welcome to my personal pages.
    #
    #        - **My site** is a simple but fast and responsive.
    #        
    #        - Do give a 🌟 on Github !
    #        
    #        - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    #editPost:
    #    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #    Text: "Suggest Changes" # edit text
    #    appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

outputs:
    home:
        - HTML
        - RSS
        - JSON