baseURL: "http://lihachev.pro/"
languageCode: "en-us"
title: "Aleksandr Likhachev"
theme: "PaperMod"

menu:
  main:
    - name: Blog
      url: /blog/
      weight: 1
    - name: Products
      url: /products/
      weight: 2
    - name: Resources
      url: /resources/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: Search
      url: /search/
      weight: 5

params:
  author: Aleksandr Likhachev

  defaultTheme: auto
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images: ["papermod-cover.png"]

  profileMode:
    enabled: true
    title: "Personal Site"
    subtitle: "Software Engineer · Finance Automation"
    imageUrl: "/images/profile.jpg"
    buttons:
      - name: Blog
        url: "/blog/"
      - name: Products
        url: "/products/"
      - name: About
        url: "/about/"

  socialIcons:
    - name: github
      url: "https://github.com/avlihachev"
    - name: twitter
      url: "https://twitter.com/lihachev"
    - name: instagram
      url: "https://instagram.com/lihachev"
    - name: linkedin
      url: "https://www.linkedin.com/in/alexander-lihachev-b893468"
    - name: facebook
      url: "https://facebook.com/lihachev"

assets:
  disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true
  x:
    enableDNT: true
    simple: true
    privacyEnhanced: true
instagram:
  disabled: false
  simple: true
youtube:
  disabled: false
  privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
